# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-20 10:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GeoRiddles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mystery',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='mystery',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='mystery',
            name='added_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
