# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeoRiddles', '0002_auto_20170520_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='mystery',
            name='image',
            field=models.ImageField(blank=True, upload_to='GeoRiddles/static/'),
        ),
    ]
